Resources:
  # Lambda can have full access to s3
  IAMS3FullAccessRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "S3FullAccessRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
            Action:
              - "sts:AssumeRole"

  IAMS3FullAccessPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "S3FullAccessPolicy"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - "s3:*"
            Resource:
              - "arn:aws:s3:::*"
      Roles:
        - !Ref IAMS3FullAccessRole

  # Redshift has read only access to "my-s3-bucket-${AWS::AccountId}-${AWS::Region}"
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "my-s3-bucket-${AWS::AccountId}-${AWS::Region}"

  BucketReadOnlyPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal: "*"
            Action:
              - s3:Get*
              - s3:List*
            Resource:
              - !Sub arn:aws:s3:::${S3Bucket}
              - !Sub arn:aws:s3:::${S3Bucket}/*

  IAMS3ReadOnlyRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: "S3ReadOnlyRole"
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - redshift.amazonaws.com
            Action:
              - "sts:AssumeRole"

  IAMS3ReadOnlyPolicy:
    Type: "AWS::IAM::Policy"
    Properties:
      PolicyName: "S3ReadOnlyAccess"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - s3:Get*
              - s3:List*
            Resource:
              - !Sub arn:aws:s3:::${S3Bucket}
              - !Sub arn:aws:s3:::${S3Bucket}/*
              - !Sub arn:aws:s3:::${S3Bucket}/*/*
      Roles:
        - !Ref IAMS3ReadOnlyRole
