Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-x86_64-gp2'
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: "Name of keypair for SSH to access the instance"

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      Keyname: !Ref KeyName
      InstanceType: "t2.micro"
      ImageId: !Ref 